server:
  port: 8003

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://10.211.55.6:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1qaz_xsw2
    druid:
      initial-size: 16
      min-idle: 16
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      connection-properties: false


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.minger.springcloud.entities    # 所有Entity别名类所在包


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true

    service-url:
      #服务提供方的eureka单机版配置
      #defaultZone: http://localhost:7001/eureka

      #服务提供方的eureka集群版配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: payment8003                              # 显示实例名，如果不加 instance-id 则显示的上面的服务名称
    prefer-ip-address: true                               # 访问路径显示IP
    lease-renewal-interval-in-seconds: 1                  # Eureka 客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-expiration-duration-in-seconds: 2               # Eureka 服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将其服务剔除