#80表示注册到zookeeper服务器的消费订单服务端口号
server:
  port: 80


#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 10.211.55.6:2181



